# Generated by Django 3.2.9 on 2021-11-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transation',
            options={'verbose_name_plural': 'Transations'},
        ),
        migrations.AlterField(
            model_name='transation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transation',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
